/**
 * Stage 6 deliverable: what the archive can and cannot compute.
 *
 * Generated from the published shards, so the list of gaps is derived rather
 * than remembered.
 *
 *   npx tsx src/trophy/archive-report.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  bestWithoutTitle, closestFinals, fallenChampions, longestStreaks, matchupResults,
  mostLopsidedMatchups, mostTiedMatchups, transactionRecords,
} from '../domain/archive.js'
import type { MatchupShard, SeasonsShard, TransactionsShard } from '../domain/trophy.js'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const SHARDS = path.join(ROOT, 'data', 'kp', 'trophy')
const read = <T>(n: string): T => JSON.parse(readFileSync(path.join(SHARDS, n), 'utf8')) as T

const shard = read<SeasonsShard>('seasons.json')
const matchups = read<MatchupShard>('matchups.json')
const transactions = read<TransactionsShard>('transactions.json')
const name = (id: string) => shard.owners.find(o => o.id === id)?.displayName ?? id

const results = matchupResults(shard, matchups)
const tx = transactionRecords(shard, transactions, 5)

const out: string[] = []
const p = (s = '') => out.push(s)

p('# Trophy Room — Stage 6 archive report')
p()
p('Generated by `npx tsx src/trophy/archive-report.ts`.')
p()

p('## What the archive computes')
p()
p('| Record | Leader |')
p('|---|---|')
const lop = mostLopsidedMatchups(results, 1)[0]!
p(`| Most lopsided matchup | ${name(lop.ownerA)} ${lop.wins}-${lop.losses}-${lop.ties} over ${name(lop.ownerB)}, ${lop.season} week ${lop.week} |`)
const tied = mostTiedMatchups(results, 1)[0]!
p(`| Most tied categories | ${name(tied.ownerA)} and ${name(tied.ownerB)}, ${tied.ties} tied, ${tied.season} week ${tied.week} |`)
const finals = closestFinals(shard, results, 3)
p(`| Closest championship finals | ${finals.filter(f => f.margin === 0).map(f => f.season).join(', ')} finished level |`)
const miss = bestWithoutTitle(shard, 1)[0]!
p(`| Best season without a title | ${name(miss.ownerId)}, ${miss.season}, ${miss.wins}-${miss.losses}-${miss.ties} (${miss.percentage}) |`)
const fallenList = fallenChampions(shard)
p(`| Champions who missed the next playoffs | ${fallenList.length}, worst ${name(fallenList[0]!.ownerId)} (${fallenList[0]!.titleSeason} champion, ${fallenList[0]!.seed} of ${fallenList[0]!.numTeams} in ${fallenList[0]!.nextSeason}) |`)
const win = longestStreaks(results, 'W', 1)[0]!
p(`| Longest winning run | ${name(win.ownerId)}, ${win.length}, ${win.from.season} week ${win.from.week} to ${win.to.season} week ${win.to.week} |`)
const loss = longestStreaks(results, 'L', 1)[0]!
p(`| Longest losing run | ${name(loss.ownerId)}, ${loss.length}, ${loss.from.season} week ${loss.from.week} to ${loss.to.season} week ${loss.to.week} |`)
p(`| Busiest season | ${name(tx.busiestSeasons[0]!.ownerId)}, ${tx.busiestSeasons[0]!.count} moves in ${tx.busiestSeasons[0]!.season} |`)
p(`| Most trades | ${name(tx.mostTrades[0]!.ownerId)}, ${tx.mostTrades[0]!.count} |`)
p(`| Most-traded player | ${tx.mostTradedPlayers[0]!.name}, ${tx.mostTradedPlayers[0]!.trades} trades |`)
p(`| Passed around the most | ${tx.mostPassedAround[0]!.name}, ${tx.mostPassedAround[0]!.owners} owners |`)
p()

p('## What could not be computed reliably')
p()
p('### A true roster history')
p()
p('"Most-rostered players across owners" is published as **players acquired by the**')
p('**most different owners**, which is a floor rather than the real figure. It is built')
p('from transaction destinations, so it counts a player who was traded, claimed or')
p('signed, and misses one who was drafted by an owner and simply kept. Closing the gap')
p('needs a weekly roster for every team in every season, which is roughly 4,800 requests')
p('and is not stored today. The column is labelled for what it actually measures.')
p()

p('### Transactions with nobody attached')
p()
p(`${tx.totals.unattributed} transactions name no team on either side and so cannot be`)
p('credited to an owner:')
p()
p(`- ${tx.totals.unattributed - tx.totals.tradesWithoutPlayers} commissioner actions, which is what that type looks like in the payload.`)
p(`- ${tx.totals.tradesWithoutPlayers} trades that name no players at all. The league allows trading draft picks, so`)
p('  that is the likely explanation, but nothing in the response says so and the report')
p('  does not claim it. They are counted in the total on file and excluded from every')
p('  per-owner figure.')
p()

p('### The 2011 undercount')
p()
for (const u of transactions.unavailable) {
  p(`- ${u.season}, list index ${u.listIndex}: ${u.reason}.`)
}
p()
p('Every transaction total for 2011 is short by exactly this many, and no workaround')
p('exists: the records fail whether requested in a page or alone.')
p()

p('### Things the data cannot answer at all')
p()
p('- **Why anything happened.** No record here infers a motive, an injury or an intent.')
p('- **Vetoed trades.** Yahoo keeps no record of a trade that was rejected, so the veto')
p('  history has to be hand-entered. That is the Stage 7 curated wing.')
p('- **Keeper tenure before 2015.** Keepers cannot be identified in the earlier seasons,')
p('  so "longest-held keeper" cannot be computed and is also curated.')
p()

p('## Conventions worth knowing')
p()
p('- Consolation games never count, here or anywhere else in the record book.')
p('- Streaks run across regular-season, championship and placement games in date order,')
p('  and carry across seasons.')
p('- A matchup where both sides took the same number of categories is a draw. It ends a')
p(`  run of either kind rather than extending one. There are ${results.filter(r => r.wins === r.losses).length} of them.`)
p('- "Missed the playoffs" is judged against that season\'s bracket, which was four teams')
p('  in 2020 and six otherwise.')
p()

mkdirSync(path.join(ROOT, 'docs', 'trophy-room'), { recursive: true })
writeFileSync(path.join(ROOT, 'docs/trophy-room/stage6-archive.md'), out.join('\n'))
console.log(out.join('\n'))
console.log('\nWrote docs/trophy-room/stage6-archive.md')
