/**
 * Stage 5 deliverable: prove the head-to-head matrix reconciles with the
 * all-time standings.
 *
 * The two are computed from different things. The standings come from Yahoo's
 * per-season outcome totals; the matrix is built by summing category results
 * out of every stored matchup. If they agree to the category across fifteen
 * owners and eighteen seasons, both are right. If they disagree, one is wrong
 * and neither should be published.
 *
 * This is how the current season's absence was caught: the standings counted
 * only seasons Yahoo had flagged finished, while the matrix counted every
 * matchup, so 2026 was in one and not the other.
 *
 *   npx tsx src/trophy/matrix-check.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  allTimeStandings, formatPct, headToHead, mostLopsided, reconcile, regularSeasonComplete,
} from '../domain/ownerStats.js'
import type { MatchupShard, SeasonsShard } from '../domain/trophy.js'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const SHARDS = path.join(ROOT, 'data', 'kp', 'trophy')
const read = <T>(name: string): T => JSON.parse(readFileSync(path.join(SHARDS, name), 'utf8')) as T

const shard = read<SeasonsShard>('seasons.json')
const matchups = read<MatchupShard>('matchups.json')
const name = (id: string) => shard.owners.find(o => o.id === id)?.displayName ?? id

const result = reconcile(shard, matchups)
const standings = allTimeStandings(shard)
const counted = shard.seasons.filter(regularSeasonComplete)

const out: string[] = []
const p = (s = '') => out.push(s)

p('# Trophy Room — Stage 5 matrix reconciliation')
p()
p(`Generated by \`npx tsx src/trophy/matrix-check.ts\`.`)
p()
p('The all-time standings and the head-to-head matrix are computed from different')
p("sources. The standings come from Yahoo's per-season outcome totals. The matrix is")
p('built by summing per-category results out of every stored matchup. Agreeing to the')
p('category across every owner is what makes both trustworthy.')
p()

p('## Seasons counted')
p()
p(`${counted.length} of ${shard.seasons.length} seasons have a complete regular season and are counted:`)
p(`${counted.map(s => s.season).join(', ')}.`)
p()
const notCounted = shard.seasons.filter(s => !regularSeasonComplete(s))
p(notCounted.length === 0
  ? 'No season is excluded. The current season counts because its regular season is over, whatever the playoff bracket is still doing.'
  : `Excluded because the regular season is not complete: ${notCounted.map(s => s.season).join(', ')}.`)
p()

p('## Reconciliation')
p()
p('| Owner | Standings | Matrix | Result |')
p('|---|---|---|---|')
for (const row of result.rows) {
  const s = row.standings
  const m = row.matrix
  p(`| ${name(row.ownerId)} | ${s.wins}-${s.losses}-${s.ties} | ${m.wins}-${m.losses}-${m.ties} | ${row.ok ? 'match' : 'MISMATCH'} |`)
}
p()
const decisions = result.rows.reduce((a, r) => a + r.standings.wins + r.standings.losses + r.standings.ties, 0)
p(result.ok
  ? `All ${result.rows.length} owners reconcile exactly, across ${decisions.toLocaleString()} category decisions.`
  : `${result.rows.filter(r => !r.ok).length} owners do NOT reconcile.`)
p()

p('## Matrix coverage')
p()
p('| Scope | Pairings with a meeting | Fewest meetings | Median | Most |')
p('|---|---|---|---|---|')
for (const scope of ['regular', 'playoffs'] as const) {
  const m = headToHead(shard, matchups, scope)
  const counts: number[] = []
  for (const a of m.ownerIds) {
    for (const b of m.ownerIds) {
      if (a >= b) continue
      const cell = m.get(a, b)
      if (cell) counts.push(cell.meetings)
    }
  }
  counts.sort((x, y) => x - y)
  p(`| ${scope === 'regular' ? 'Regular season' : 'Playoffs'} | ${counts.length} | ${counts[0]} | ${counts[Math.floor(counts.length / 2)]} | ${counts[counts.length - 1]} |`)
}
p()
p('Playoff samples are small by nature, which is why the two scopes are separate tabs')
p('rather than one combined number, and why the lopsided-rivalry callout states the')
p('minimum number of meetings it required.')
p()

p('## Most lopsided')
p()
p('| Scope | Minimum meetings | Rivalry |')
p('|---|---|---|')
for (const [scope, minimum] of [['regular', 15], ['playoffs', 4]] as const) {
  const m = headToHead(shard, matchups, scope)
  const r = mostLopsided(m, minimum)
  p(`| ${scope === 'regular' ? 'Regular season' : 'Playoffs'} | ${minimum} | ` +
    (r
      ? `${name(r.a)} over ${name(r.b)}, ${r.record.wins}-${r.record.losses}-${r.record.ties} in ${r.record.meetings} meetings (${formatPct(r.record.percentage)})`
      : 'no pairing meets the minimum') + ' |')
}
p()

p('## All-time standings')
p()
p('| Owner | Seasons | Record | Pct | Playoffs | Titles | Runner-up | Last | Avg finish |')
p('|---|---|---|---|---|---|---|---|---|')
for (const r of standings) {
  p(`| ${name(r.ownerId)}${r.active ? '' : ' (departed)'} | ${r.seasonsPlayed} | ${r.wins}-${r.losses}-${r.ties} | ${formatPct(r.percentage)} | ${r.playoffAppearances} | ${r.titles} | ${r.runnerUps} | ${r.lastPlaces} | ${r.averageFinish.toFixed(2)} |`)
}
p()

mkdirSync(path.join(ROOT, 'docs', 'trophy-room'), { recursive: true })
writeFileSync(path.join(ROOT, 'docs/trophy-room/stage5-matrix-check.md'), out.join('\n'))
console.log(out.join('\n'))
console.log('\nWrote docs/trophy-room/stage5-matrix-check.md')
if (!result.ok) process.exit(1)
