/**
 * Stage 4 deliverable: the distributions behind the record qualifiers, and
 * what each candidate threshold does to the leaderboards.
 *
 * Generated from the same constants the page uses, so the proposal and the
 * implementation cannot drift apart.
 *
 *   npx tsx src/trophy/qualifiers-report.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { BRACKET_BY_CODE, type SeasonsShard, type WeeklyShard } from '../domain/trophy.js'
import { QUALIFIERS, countsTowardRecords, type TeamWeek } from '../domain/records.js'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const SHARDS = path.join(ROOT, 'data', 'kp', 'trophy')
const read = <T>(name: string): T => JSON.parse(readFileSync(path.join(SHARDS, name), 'utf8')) as T

const seasonsShard = read<SeasonsShard>('seasons.json')
const weekly = read<WeeklyShard>('weekly.json')
const col = (n: string) => weekly.columns.indexOf(n)
const statNames = seasonsShard.seasons[0]!.categories.map(c => c.abbr)
const ownerName = (i: number) => seasonsShard.owners[i]?.displayName ?? `#${i}`

const weeks: TeamWeek[] = weekly.rows.map(r => ({
  season: r[col('season')] as number,
  week: r[col('week')] as number,
  ownerIndex: r[col('owner')] as number,
  days: r[col('days')] as number,
  bracket: BRACKET_BY_CODE[r[col('bracket')] as number]!,
  values: Object.fromEntries(statNames.map(n => [n, r[col(n)] ?? null])),
  ab: r[col('ab')] ?? null,
  ip: r[col('ip')] ?? null,
  completedGames: r[col('completedGames')] ?? null,
}))

const included = weeks.filter(w => countsTowardRecords(w.bracket))
const standard = included.filter(w => w.days === 7)

const pct = (n: number, of: number) => `${((100 * n) / of).toFixed(1)}%`
const quantile = (sorted: number[], q: number) => sorted[Math.min(sorted.length - 1, Math.floor(q * sorted.length))]!

const out: string[] = []
const p = (s = '') => out.push(s)

p('# Trophy Room — Stage 4 qualifier proposal')
p()
p(`Generated by \`npx tsx src/trophy/qualifiers-report.ts\` from the published shards.`)
p('The thresholds below are the ones `src/domain/records.ts` uses, so this document and the page cannot disagree.')
p()

p('## Proposal')
p()
p('| Category | Qualifier | Keeps |')
p('|---|---|---|')
for (const [abbr, q] of Object.entries(QUALIFIERS)) {
  const field = q.minIp !== undefined ? 'ip' : 'ab'
  const min = q.minIp ?? q.minAb!
  const withField = standard.filter(w => w[field as 'ip' | 'ab'] !== null)
  const keep = withField.filter(w => (w[field as 'ip' | 'ab'] as number) >= min)
  p(`| ${abbr} | minimum ${min} ${q.minIp !== undefined ? 'IP' : 'AB'} | ${keep.length} of ${withField.length} (${pct(keep.length, withField.length)}) |`)
}
p()

p('## Which weeks are in the pool')
p()
const byBracket = new Map<string, number>()
for (const w of weeks) byBracket.set(w.bracket, (byBracket.get(w.bracket) ?? 0) + 1)
p('| Bracket | Team-weeks | Counts toward records |')
p('|---|---|---|')
for (const [bracket, n] of [...byBracket].sort((a, b) => b[1] - a[1])) {
  p(`| ${bracket} | ${n} | ${countsTowardRecords(bracket) ? 'yes' : 'no'} |`)
}
p()
p(`${included.length} of ${weeks.length} team-weeks count. Of those, ${standard.length} fall in a standard seven-day week, which is the default mode.`)
p()

// ---------------------------------------------------------------- innings
p('## Innings pitched')
p()
const ips = standard.map(w => w.ip).filter((v): v is number => v !== null).sort((a, b) => a - b)
p('| Percentile | IP |')
p('|---|---|')
for (const q of [0, 0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 1]) {
  p(`| ${(q * 100).toFixed(0)} | ${quantile(ips, q === 1 ? 0.999 : q).toFixed(1)} |`)
}
p()
p('A normal week runs 40 to 60 innings. The tail below 25 is where the unqualified records come from.')
p()

// -------------------------------------------------------------- thresholds
function board(abbr: string, higherIsBetter: boolean, field: 'ip' | 'ab', thresholds: number[]) {
  p(`### ${abbr}`)
  p()
  p(`| Minimum ${field.toUpperCase()} | Top five |`)
  p('|---|---|')
  for (const t of thresholds) {
    const pool = standard
      .filter(w => w.values[abbr] !== null && w[field] !== null && (w[field] as number) >= t)
      .sort((a, b) => (higherIsBetter ? b.values[abbr]! - a.values[abbr]! : a.values[abbr]! - b.values[abbr]!))
      .slice(0, 5)
    const cells = pool.map(w =>
      `${w.values[abbr]!.toFixed(abbr === 'AVG' || abbr === 'OBP' ? 3 : 2)} ` +
      `(${ownerName(w.ownerIndex)} ${w.season} wk ${w.week}, ${Math.round(w[field] as number)} ${field.toUpperCase()})`,
    )
    const chosen = QUALIFIERS[abbr]?.minIp === t || QUALIFIERS[abbr]?.minAb === t
    p(`| ${t}${chosen ? ' **(proposed)**' : ''} | ${cells.join('; ')} |`)
  }
  p()
}

p('## What each threshold does to the board')
p()
board('ERA', false, 'ip', [0, 20, 25, 30, 35, 40])
board('WHIP', false, 'ip', [0, 20, 25, 30, 35, 40])
p('At 25 innings both boards stop changing. Thirty and thirty-five produce the same five; forty starts evicting genuine records. Below 25 sit 0.00 earned-run averages over nine and seventeen innings.')
p()

// ------------------------------------------------------------------ at-bats
p('## At-bats')
p()
const abSeasons = [...new Set(standard.filter(w => w.ab !== null).map(w => w.season))].sort()
p(`Yahoo only carries a hits-over-at-bats display stat from ${abSeasons[0]}, so at-bats exist for ${abSeasons.join(', ')} and for no earlier season.`)
p()
p('**Those seasons are taken as having met the minimum rather than dropped.** Losing fourteen seasons of batting records to a missing column would cost far more than it protects, and the data supports the assumption in both directions.')
p()
const withAb = standard.filter(w => w.ab !== null)
const shortFull = withAb.filter(w => (w.ab as number) < 150 && (w.completedGames ?? 0) > 60)
p(`Where the count does exist, ${withAb.length} standard team-weeks, only ${shortFull.length} full week falls below the bar:`)
p()
for (const w of shortFull) {
  p(`- ${ownerName(w.ownerIndex)} ${w.season} week ${w.week}: ${Math.round(w.ab as number)} at-bats over ${w.completedGames} completed games, batting ${w.values['AVG']!.toFixed(3)}.`)
}
p()
p('And nothing at the top of the pre-2023 boards rests on a thin sample. The leading weeks:')
p()
const preLeaders = standard
  .filter(w => w.ab === null && w.values['AVG'] !== null)
  .sort((a, b) => b.values['AVG']! - a.values['AVG']!)
  .slice(0, 5)
for (const w of preLeaders) {
  p(`- ${w.values['AVG']!.toFixed(3)}, ${ownerName(w.ownerIndex)} ${w.season} week ${w.week}, ${w.completedGames} completed games.`)
}
p()
p('A normal week is 85 to 100 completed games, so every one of those is a full week. The one case the assumption must not cover is a team that started nobody, and that is excluded explicitly: a week with no completed games never qualifies for a rate.')
p()
const abs = standard.map(w => w.ab).filter((v): v is number => v !== null).sort((a, b) => a - b)
p('| Percentile | AB |')
p('|---|---|')
for (const q of [0, 0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 1]) {
  p(`| ${(q * 100).toFixed(0)} | ${Math.round(quantile(abs, q === 1 ? 0.999 : q))} |`)
}
p()
board('AVG', true, 'ab', [0, 125, 150, 175, 200])
board('OBP', true, 'ab', [0, 125, 150, 175, 200])
p('The AVG board is identical from zero through 175, so the threshold costs nothing there. OBP is the one that needs it: unqualified it is led by a partial week on 85 at-bats. Two hundred starts evicting real weeks.')
p()

// ---------------------------------------------------------------- ties
p('## Ties')
p()
p('Several categories have hundreds of team-weeks tied on zero, so a "top five" there is an arbitrary slice of a much larger tie.')
p()
p('| Category | Team-weeks tied on the best value | Value |')
p('|---|---|---|')
for (const abbr of statNames) {
  const cat = seasonsShard.seasons[0]!.categories.find(c => c.abbr === abbr)!
  const vals = standard.map(w => w.values[abbr]).filter((v): v is number => v !== null)
  if (vals.length === 0) continue
  const best = cat.higherIsBetter ? Math.max(...vals) : Math.min(...vals)
  const n = vals.filter(v => v === best).length
  if (n >= 5) p(`| ${abbr} | ${n} | ${best} |`)
}
p()
p('So tied rows share a rank, are ordered oldest first so the same five come back every time, and each table says how many team-weeks share the value at the cut.')
p()

// ------------------------------------------------------- zero-game weeks
p('## Weeks where a team started nobody')
p()
const zero = weeks.filter(w => w.completedGames === 0)
p('| Season | Week | Owner | Bracket | Counts |')
p('|---|---|---|---|---|')
for (const w of zero) {
  p(`| ${w.season} | ${w.week} | ${ownerName(w.ownerIndex)} | ${w.bracket} | ${countsTowardRecords(w.bracket) ? 'yes' : 'no'} |`)
}
p()
p('These are real results rather than gaps: the roster was in place and every player was benched. The one that counts is the outright worst week on record for runs, runs batted in and strikeouts, and it is tagged on the page so nobody reads it as a typo.')
p()

mkdirSync(path.join(ROOT, 'docs', 'trophy-room'), { recursive: true })
writeFileSync(path.join(ROOT, 'docs/trophy-room/stage4-qualifiers.md'), out.join('\n'))
console.log(out.join('\n'))
console.log('\nWrote docs/trophy-room/stage4-qualifiers.md')
